workflows:
  expo-android-apk:
    name: Expo Android APK
    environment:
      node: 18
      vars:
        EXPO_TOKEN: EIijYxu8KjSPAt8g0HGdgVBySDQpZcHzJwIVMMtY
    scripts:
      - name: Install dependencies
        script: npm install --legacy-peer-deps
      - name: Build Android APK on Expo Cloud
        script: |
          npm install -g eas-cli
          eas build -p android --profile preview --non-interactive
